### ISSUE TITLE
Cross.png not liked by older versions of tkinter.....  would 💗 to see screenshots in your readme!

### ISSUE THREAD

**Issue by PySimpleGUI** [feklisoff/python-gui-experiments#1]
I love these apps!

If you've got a moment, drop some screenshots in your readme.

![image](https://user-images.githubusercontent.com/46163555/164993760-8d901d1c-ccc2-420e-bab6-e6a30224638f.png)

I had trouble with your cross.png file when using older tkinter version (I tried 8.6.6).  It generates this error from PySimpleGUI.

![image](https://user-images.githubusercontent.com/46163555/164993869-77b5d2b4-44da-4de6-af1e-4ab66e33ad06.png)

I opened with Paint.net and resaved it and it was fine.  It worked OK with the newer version of tkinter.

![cross1](https://user-images.githubusercontent.com/46163555/164993888-3ce29a88-b0fc-4c61-9397-ceed703d7ae9.png)

Also made this base64 string from it should you want to include in code sometime.

```python
cross = b'iVBORw0KGgoAAAANSUhEUgAAACgAAAAoCAYAAACM/rhtAAACwElEQVR4nO2YP2gUURDGf5OchkSx8w8iGkFQDIK6t4UgmtbA7VVprERC1EYE7RRB0MoqjQpBUlkFhOxZKFgoNmL2BIVoYRFFJKKl0RCjjkWiibnbN+9t4Gwy1d2bme/7+Obd3tsHq7GykFaSabV8EeUqMEXHTLeMTny3elomUJPyNLCuSWZI0vq5vL5cgZqUdbFKTsrY+MgKxD0CjrpqJM2aamm6qH0HdlBqf9scSbbL2Ph7b3H9hzqZnftmFzIgtey2l0BY5mBjfJY02+Ql0I2zKCTHwTYH9CsH3kZNyl8tUq1GZ01lAKpN9uZ85AqUtN5jwHZppXzLTSxDBgagw1Kr524Bh4MA+sGZFk7ldlbiO4ayeYi0PujKOwVKWt9mEeTuMdHjVm/evlsahoOAcMkq0eTgrn+/l1+auCXdatbgIVDGsmseMG+WLewzUD/J3fqUjevjIH6j0Ep8AvweK5KOb/bhBU+BC7AP3Gkd0aT81IRpb9vtzxn4X+z70HUSekxjaQQ4CHTsLAXVL4tQcRAoUEZHfwKToSQLYf+ym3EWaSoy6iLuQeiI/4aeD2x4WIxnBQfWEBeLugeFHWxdtESgVqI9RXsLCdQkPhLUIPK6CA8U/5E8Du5I4htFmIIFaiU6XIQI9EyRrnAHRZ4UIYJiz88ggZpEE6EEDRjV+HJIvbdA7e0tgex1Fv1q249ScwPpFV9OCHFww/ScUfFc7j17IbUsAZxvfCGj9hKoSZxZNZJm0ZLP603ManTdh9sUqIPRGtDIKLvfsJJmbmyVCxY3+Dj4UewbqDQ71rAGCjrs6vMZtVOgVqMBCwCYyUtY77wA2t/j3A7WGJwOzIvIuoy8+yQz2/nFlbZuFlz3MwA/jPwCTP7dC/zZ583D65ymSTQJ0t3QHHDO0754CyV9B6wNwQl9q7sJnA4Vtxr/M34DYiDT2TtHLPgAAAAASUVORK5CYII='

```

You can use it in your `Image` element just like a filename (sorry if you already knew all this)

```python
sg.Image(cross, pad=0, enable_events=True, key='-CLOSE-')
```

Thanks for the entertainment!  Fun stuff!  It's nice to see you writing original code and experimenting.   Love it!  ![image](https://user-images.githubusercontent.com/46163555/164993983-fc82279d-b18b-4424-9bae-b6b779485f5e.png)

**Comment by feklisoff** [comment]
Hey, thanks, I've implemented your suggestions and you can see the screens now as well

**Comment by PySimpleGUI** [comment]
Oh wow!

I hadn't tried the YouTube converter.  VERY nice work!
![image](https://user-images.githubusercontent.com/46163555/165310512-8589fed0-27b0-4415-9505-32beb27c55f1.png)

I really like that you're experimenting with color, tried out the match statement in the event loop, ....

I'm genuinely impressed.
